---
  - name: Provision an EC2 Instance.
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning

    vars_files:
     - defaults/main.yml
    tasks:
 
      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: basic_firewall
        
      - name: Launching  new EC2 Instance
        local_action: ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true
                      wait_timeout=500 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
        register: ec2_my_aws
 
      - name: Add created EC2 instance to local hosts.txt
        local_action: lineinfile 
                      path=hosts.txt
                      regexp={{ item.public_ip }} 
                      insertafter='\[wordpress\]' 
                      line='ip_or_domain_your_server    ansible_host={{ item.public_ip }}'
        with_items: '{{ec2_my_aws.instances}}'
 
      - name: Add new instance to host group
        add_host:
          hostname: "{{ item.public_ip }}"
          groupname: launched
        with_items: "{{ ec2_my_aws.instances }}"
 
      - name: Whait ssh connection
        local_action: wait_for 
                      host={{ item.public_ip }} 
                      port=22 
                      state=started
        with_items: '{{ ec2_my_aws.instances }}'
 
      - name: Add tag to Instance(s)
        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
        with_items: '{{ ec2_my_aws.instances }}'
        args:
          tags:
            Name: ec2_my_aws
